config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :builds do
    resources :combinations, only: %i[new create]
  end
  resources :combinations, only: :destroy
  resources :charms, only: %i[index show]

  root to: 'builds#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/build.rb
class Build < ApplicationRecord
  has_many :combinations, dependent: :destroy
  has_many :charms, through: :combinations

  validates :name, presence: true, uniqueness: true

  def notches
    notches = 0
    charms.each { |charm| notches += charm.notches }
    notches
  end

  def overcharmed?
    notches > 11
  end

  def self.search(search)
    return Build.all unless search

    @builds = Build.joins(:combinations).joins(:charms).where('builds.name ILIKE ? OR charms.name ILIKE ?', "%#{search}%", "%#{search}%")
  end
end

app/models/charm.rb
class Charm < ApplicationRecord
  mount_uploader :sprite, SpriteUploader

  has_many :combinations
  has_many :builds, through: :combinations

  validates :name, presence: true
  validates :notches, presence: true, numericality: { only_integer: true }
  validates :description, presence: true
end

app/models/combination.rb
class Combination < ApplicationRecord
  belongs_to :charm
  belongs_to :build

  validates :charm_id, presence: true, uniqueness: { scope: :build_id }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/builds_controller.rb
class BuildsController < ApplicationController
  before_action :set_build, only: %i[show edit update destroy]

  def index
    @builds = Build.search(params[:search])
  end

  def show
    @combination = Combination.new
  end

  def new
    @build = Build.new
  end

  def create
    @build = Build.new(build_params)
    if @build.save
      redirect_to build_path(@build)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @build.update(build_params)
    if @build.save
      redirect_to build_path(@build)
    else
      render :edit
    end
  end

  def destroy
    @build.destroy
    redirect_to builds_path
  end

  private

  def set_build
    @build = Build.find(params[:id])
  end

  def build_params
    params.require(:build).permit(:name, :description, :search)
  end
end

app/controllers/charms_controller.rb
class CharmsController < ApplicationController
  def index
    @charms = Charm.all
  end
end

app/controllers/combinations_controller.rb
class CombinationsController < ApplicationController
  before_action :set_build, only: %i[new create]

  def new
    @combination = Combination.new
  end

  def create
    @combination = Combination.new(combination_params)
    @combination.build = @build
    if @combination.save
      redirect_to build_path(@build)
    else
      render 'builds/show'
    end
  end

  def destroy
    @combination = Combination.find(params[:id])
    @combination.destroy
    redirect_to build_path(@combination.build)
  end

  private

  def set_build
    @build = Build.find(params[:build_id])
  end

  def combination_params
    params.require(:combination).permit(:build_id, :charm_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/builds_helper.rb
module BuildsHelper
  def set_background(notches)
    image_url 'overcharm.png' if notches > 11
  end
end

app/helpers/charms_helper.rb
module CharmsHelper
end

app/helpers/combinations_helper.rb
module CombinationsHelper
end

app/views/builds/_form.html.erb
<%= simple_form_for @build do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <% if @build.id.nil? %>
    <%= f.submit 'Create', class: 'button' %>
  <% else %>
    <%= f.submit 'Update', class: 'button' %>
  <% end %>
<% end %>

app/views/builds/edit.html.erb
<div class="background" style="background-image: url(<%= image_url 'background.jpg' %>)">
  <div class="new-header">
    <%= render 'layouts/navbar' %>
  </div>

  <div class="container build-form edit-build-form">
    <%= render 'form' %>
  </div>
</div>

app/views/builds/index.html.erb
<div class="banner d-flex flex-column align-items-center" style="background-image: url(<%= image_url 'banner.jpg' %>)">
  <div class="banner-logo">
    <div class="d-flex justify-content-around">
      <%= image_tag 'banner_top.png', height: 25 %>
    </div>
    <h1 class="mx-auto text-center mb-2" id="title"><%= link_to 'Overcharmed', builds_path %></h1>
    <div class="d-flex justify-content-around">
      <%= image_tag 'banner_bottom.png', height: 75, class: 'mb-4' %>
    </div>
    <p class="text-center"><em>A collection of Hollow Knight <%= link_to 'charm', charms_path %> builds for any situation.</em></p>
    <div class="banner-forms mx-auto">
      <%= form_tag(builds_path, method: :get, class: 'mx-2') do %>
        <%= text_field_tag :search, params[:search], placeholder: 'Search by build or charm', class: 'form-control search-bar mr-2' %>
      <% end %>
      <%= link_to 'Create a build', new_build_path, class: "button banner-button" %>
    </div>
  </div>
</div>

<div class="py-5" style="background-color: black; min-height: 100%">
  <div class="d-flex align-items-center justify-content-around">
    <%= image_tag 'hk_border.png', height: 50, class: "mb-4" %>
  </div>

  <div class="container">
    <% if @builds.empty? %>
      <p class="text-center">No builds found :(</p>
    <% else %>
      <div class="build-cards d-flex flex-wrap justify-content-around">
        <% @builds.uniq.each do |build| %>
          <div class="build-card mb-3">
            <div class="d-flex justify-content-around"><%= image_tag 'king_header.png', width: 300 %></div>
            <% if build.overcharmed? %>
              <h2 class="text-center overcharmed"><%= link_to build.name, build_path(build) %></h2>
            <% else %>
              <h2 class="text-center"><%= link_to build.name, build_path(build) %></h2>
            <% end %>
            <div class="d-flex justify-content-around"><%= image_tag 'bottom_border.png', height: 20, class: 'mb-3' %></div>
            <div class="d-flex justify-content-around flex-wrap">
              <% build.charms.each do |charm|
                %>
                  <div class="build-sprites charm-card">
                    <p class="charm-name"><%= charm.name %></p>
                    <%= image_tag charm.sprite.url %>
                  </div>
              <% end %>
            </div>
            <div class="d-flex justify-content-around"><%= image_tag 'king_footer.png', width: 150, class: 'mt-3' %></div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/builds/new.html.erb
<div class="background" style="background-image: url(<%= image_url 'background.jpg' %>)">
  <div class="new-header">
    <%= render 'layouts/navbar' %>
  </div>

  <div class="container build-form new-build-form">
    <%= render 'form' %>
  </div>
</div>

app/views/builds/show.html.erb
<div class="background" style="background-image: url(<%= image_url 'background.jpg' %>)">
  <div class="show-header">
    <%= render 'layouts/navbar' %>
  </div>

  <div class="container">
    <div class="d-flex justify-content-around">
      <div class="build-show-header d-flex align-items-center">
        <% if @build.overcharmed? %>
          <h2 id="build-name" class="overcharmed"><%= @build.name %></h2>
        <% else %>
          <h2 id="build-name"><%= @build.name %></h2>
        <% end %>
        <%= link_to edit_build_path(@build) do %>
          <i class="fas fa-feather-alt ml-3"></i>
        <% end %>
        <%= link_to build_path(@build), method: :delete, data: { confirm: 'Are you sure?' } do %>
          <i class="fas fa-times ml-2"></i>
        <% end %>
      </div>
    </div>
    <div class="d-flex justify-content-around">
        <%= image_tag 'bottom_border.png', height: 30, class: 'mb-3' %>
    </div>

    <div class="build-charms d-flex flex-wrap mb-2" style="background-image: url(<%= set_background(@build.notches) %>)">
      <% @build.combinations.each do |combination| %>
          <%= link_to combination_path(combination), method: :delete, data: { confirm: 'Remove this charm?' } do %>
            <div class="charm-card">
              <p class="charm-name"><%= combination.charm.name %></p>
              <%= image_tag combination.charm.sprite.url, class: 'build-charm' %>
            </div>
          <% end %>
      <% end %>
    </div>

    <div class="build-capacity d-flex">
      <% capacity = @build.notches %>
      <% notches = [] %>
      <% if capacity <= 11 %>
        <% capacity.times { notches << 'full_notch.png' } %>
        <% (11 - capacity).times { notches << 'empty_notch.png' } %>
      <% else %>
        <% 11.times { notches << 'full_notch.png' } %>
        <% (capacity - 11).times { notches << 'overcharm_notch.png' } %>
      <% end %>

      <div class="notches d-flex align-items-center flex-wrap mb-3">
        <% notches.each do |notch| %>
          <%= image_tag notch, class: 'notch' %>
        <% end %>
      </div>
    </div>

    <div class="build-info">
      <div class="d-flex justify-content-around mb-2">
        <%= image_tag 'content_top.png', height: 40 %>
      </div>
      <% if @build.description == '' %>
        <p class="text-center"><em>No description available.</em></p>
      <% else %>
        <p class="text-center"><em><%= @build.description %></em></p>
      <% end %>
      <div class="d-flex justify-content-around">
        <%= image_tag 'content_bottom.png', height: 20, class: 'mb-5' %>
      </div>
      <h3 class="text-center" id="charm-title"><%= link_to 'Charms', charms_path %></h3>
      <div class="d-flex justify-content-around">
        <%= image_tag 'bottom_border.png', height: 30, class: 'mb-3' %>
      </div>
      <% @build.charms.each_with_index do |charm, index| %>
        <p><%= index + 1 %>. <b><%= charm.name %></b> - <%= charm.description %></p>
      <% end %>
    </div>

    <div class="charm-form">
      <div class="d-flex justify-content-around mt-5">
        <%= image_tag 'content_top.png', height: 40, class: 'mb-3' %>
      </div>
      <% if @build.notches == 11 %>
        <p class="full-error text-center">All notches full!</p>
      <% elsif @build.overcharmed? %>
        <p class="overcharm-error text-center">You're overcharmed!</p>
      <% else %>
        <div class="add-charm-form">
          <%= render 'combinations/form' %>
        </div>
      <% end %>
      <div class="d-flex justify-content-around">
        <%= image_tag 'content_bottom.png', height: 20, class: 'my-3' %>
      </div>
    </div>
  </div>
</div>

app/views/charms/index.html.erb
<div class="background" style="background-image: url(<%= image_url 'background.jpg' %>)">
  <%= render 'layouts/navbar' %>

  <div class="charms-header">
    <h2 class="text-center">Charms</h2>
    <div class="d-flex justify-content-around">
      <%= image_tag 'bottom_border.png', height: 30, class: 'mb-3' %>
    </div>
    <div class="d-flex justify-content-around">
      <%= image_tag 'charm.png', height: 250, class: 'mb-3' %>
    </div>
  </div>

  <div class="container pb-4">
    <div class="d-flex justify-content-around mb-3">
      <%= image_tag 'content_top.png', height: 50 %>
    </div>
    <table class="charms-table">
      <tr>
        <th><p class="text-center">Charm</p></th>
        <th><p class="text-center">Name & Effect</p></th>
        <th><p class="text-center">Notches</p></th>
      </tr>
      <% @charms.each do |charm| %>
        <tr>
          <td class="table-sprite"><div class="text-center"><%= image_tag charm.sprite.url %></div></td>
          <td class="table-details">
            <p>
              <b><%= charm.name %></b><br>
              <em><%= charm.description %></em>
            </p>
          </td>
          <td class="table-notches">
            <div class="text-center">
              <% charm.notches.times do %>
                <%= image_tag 'full_notch.png', width: 20 %>
              <% end %>
            </div>
          </td>
        </tr>
      <% end %>
    </table>
    <div class="d-flex justify-content-around">
      <%= image_tag 'content_bottom.png', height: 30, class: 'my-3' %>
    </div>
  </div>
</div>

app/views/combinations/_form.html.erb
<% valid_charms = Charm.all.reject { |charm| charm.name == 'Void Heart'} %>

<%= simple_form_for [@build, @combination] do |f| %>
  <%= f.input_field :charm_id, as: :radio_buttons, wrapper: :vertical_collection_inline, collection: valid_charms.map { |charm| ["<div class='charm-card'><p class='charm-name'>#{charm.name}</p>#{image_tag(charm.sprite.url)}</div>".html_safe, charm.id] } %>
  <div class="d-flex align-items-center justify-content-around">
    <%= f.submit 'Add charm', class: 'mb-3 button' %>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<div class="header d-flex justify-content-between align-items-center mb-3 px-5 py-3">
  <h1><%= link_to 'Overcharmed', builds_path %></h1>
  <div class="d-flex align-items-center justify-content-between">
  <%= form_tag(builds_path, method: :get, class: 'mx-4') do %>
    <%= text_field_tag :search, params[:search], placeholder: 'Search by build or charm', class: 'form-control search-bar navbar-search' %>
  <% end %>
  <%= link_to 'Create a build', new_build_path, class: 'button d-none d-md-block' %>
  <%= link_to new_build_path, class: 'd-block d-md-none' do %>
    <%= image_tag 'salubra_add.png', width: 50 %>
  <% end %>
  </div>
</div>
<div class="d-flex justify-content-around">
  <%= image_tag 'hk_border.png', height: 75, class: 'mb-3' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Overcharmed</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimum-scale=1.0, maximum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

  </head>

  <body>
    <%= yield %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </body>
</html>